name = "long/cardano_contract"
version = "0.0.0"
compiler = "v1.1.0"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'long/cardano_contract'"

[repository]
user = "long"
project = "cardano_contract"
platform = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.1"
source = "github"
[config] 



[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.1-beta"
source = "github"


[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
